### PR TITLE
[FIX] purchase_stock_ux: _bom_find error during migration

### PR DESCRIPTION
**Pull request by augusto-weiss**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/purchase/pull/157).

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
ingadhoc/purchase#158

**Pull request closed without merging**
