### PR TITLE
[FIX] purchase_ux: restore action_rfq_send button native visibility in PO

### PR DESCRIPTION
**Pull request by ced-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/232).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#233

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#233

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#233

**Pull request closed without merging**
