### PR TITLE
[FIX] purchase_stock_ux: user_id assignment on PO

### PR DESCRIPTION
**Pull request by ced-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/215).

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#216

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#216

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#216

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#216

**Pull request closed without merging**
