### PR TITLE
[FW][FIX] purchase_stock_ux: _bom_find error during migration

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/purchase#157

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/purchase/pull/158).

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this PR targets 16.0 and is the last of the forward-port chain.

To merge the full chain, say
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@augusto-weiss @vib-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by vib-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
