### PR TITLE
[IMP] purchase_stock: Set main seller as default supplier in replenishment rules

### PR DESCRIPTION
**Pull request by bruno-zanotti**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/195).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
I'm sorry, @Bruno-Zanotti: you can't review+.

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Comment by fw-bot-adhoc** [comment]
@Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#196

**Pull request closed without merging**
