### PR TITLE
[FW][IMP] purchase_ux: account_move refactor

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Created a new 'get_product_lines_to_update' method to make it easier
to inherit from the 'update_prices_with_supplier_cost' method

Forward-Port-Of: ingadhoc/purchase#146

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/purchase/pull/147).

**Comment by fw-bot-adhoc** [comment]
Ping @ica-adhoc, @nicomacr cherrypicking of pull request ingadhoc/purchase#146 failed.

stdout:
```
Auto-merging purchase_ux/models/account_move.py
CONFLICT (content): Merge conflict in purchase_ux/models/account_move.py

```

stderr:
```
15:59:44.806292 git.c:439               trace: built-in: git cherry-pick 0cc989da645376dcd5903520f6fa53235d72f75c
error: could not apply 0cc989d... [IMP] purchase_ux: account_move refactor
hint: after resolving the conflicts, mark the corrected paths
hint: with 'git add <paths>' or 'git rm <paths>'
hint: and commit the result with 'git commit'
----------
status:

```

Either perform the forward-port manually (and push to this branch, proceeding as usual) or close this PR (maybe?).

In the former case, you may want to edit this PR message as well.

**Comment by nicomacr** [comment]
@ica-adhoc podes revisar este FP

**Comment by ica-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
