### PR TITLE
[IMP] purchase_ux: account_move refactor

### PR DESCRIPTION
**Pull request by ica-adhoc**
Created a new 'get_product_lines_to_update' method to make it easier
to inherit from the 'update_prices_with_supplier_cost' method

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/purchase/pull/146).

**Comment by zaoral** [comment]
@roboadhoc override=<status>

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. You are not allowed to override this status.

**Comment by zaoral** [comment]
@roboadhoc override=ci/oba_without_tests
@roboadhoc override=ci/personalizations

**Comment by roboadhoc** [comment]
I'm sorry, @zaoral. You are not allowed to override this status. You are not allowed to override this status.

**Comment by zaoral** [comment]
we override the ci results because we have external errors not related to this pr

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests r+

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Comment by roboadhoc** [comment]
@nicomacr, you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/purchase#147

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/purchase#147

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/purchase#147

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/purchase#147

**Comment by fw-bot-adhoc** [comment]
This pull request has forward-port PRs awaiting action (not merged or closed): ingadhoc/purchase#147

**Pull request closed without merging**
