### PR TITLE
[FIX]purchase_ux:revert change

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/178).

**Comment by augusto-weiss** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @augusto-weiss this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#181

**Pull request closed without merging**
