### PR TITLE
[FIX]purchase_stock_ux:domain in method

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/199).

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#200

**Pull request closed without merging**
