### PR TITLE
[FW][ADD]purchase_stock_ux: user_id from replen

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/purchase#185

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/192).

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by mav-adhoc** [comment]
@jcadhoc Fijate si habría que agregarlo y hacerle un rebase!

**Comment by fw-bot-adhoc** [comment]
@jcadhoc @mav-adhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
