### PR TITLE
[FIX] purchase_stock_ux: Use line uom to validate the update qty on the run procurement.

### PR DESCRIPTION
**Pull request by nicomacr**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://runbot.adhoc.com.ar/ingadhoc/purchase/pull/148).

**Comment by nicomacr** [comment]
@roboadhoc r+

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by roboadhoc** [comment]
I'm sorry, @nicomacr. You are not allowed to override this status.

**Comment by nicomacr** [comment]
@roboadhoc override=ci/oba_without_tests

**Comment by nicomacr** [comment]
mezclamos sin pasar el test por que es un warning y no depende de este cambio

**Comment by nicomacr** [comment]
@roboadhoc p=0

**Pull request closed without merging**
