### PR TITLE
[MIG] purchase_ux: Migration to 17.0

### PR DESCRIPTION
**Pull request by jcadhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/191).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc because this PR has multiple commits, I need to know how to merge it:

* `merge` to merge directly, using the PR as merge commit message
* `rebase-merge` to rebase and merge, using the PR as merge commit message
* `rebase-ff` to rebase and fast-forward

**Comment by mav-adhoc** [comment]
@roboadhoc rebase-ff

**Comment by roboadhoc** [comment]
Merge method set to rebase and fast-forward.

**Comment by roboadhoc** [comment]
@jcadhoc @mav-adhoc unable to stage: commits with multiple parents (0c45b8452dc7c21ebc007d75b1a3c6621906bead) can not be rebased, either fix the branch to remove merges or merge without rebasing

**Comment by mav-adhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
