### PR TITLE
[FIX]purchase_stock_ux: attrs in views

### PR DESCRIPTION
**Pull request by mav-adhoc**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/212).

**Comment by jcadhoc** [comment]
@roboadhoc r+ override=ci/runbot-oba

**Comment by roboadhoc** [comment]
@jcadhoc you may want to rebuild or fix this PR as it has failed CI.

**Comment by roboadhoc** [comment]
I'm sorry, @jcadhoc: you are not allowed to override this status.

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
