### PR TITLE
[FW][ADD] purchase_order_line_number: module to numbering purchase order lines

### PR DESCRIPTION
**Pull request by fw-bot-adhoc**
Forward-Port-Of: ingadhoc/purchase#206

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/210).

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc this PR targets 17.0 and is the last of the forward-port chain.

To merge the full chain, use
> @fw-bot-adhoc r+

More info at https://github.com/odoo/odoo/wiki/Mergebot#forward-port

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc ci/runbot-oba failed on this forward-port PR

**Comment by fw-bot-adhoc** [comment]
@ced-adhoc @jcadhoc this PR was modified / updated and has become a normal PR. It should be merged the normal way (via @roboadhoc)

**Comment by jcadhoc** [comment]
@roboadhoc r+

**Pull request closed without merging**
