### PR TITLE
[IMP] _quotation_products: show by default stock on location

### PR DESCRIPTION
**Pull request by jjscarafia**

### CODE REVIEW

**Comment by roboadhoc** [comment]
[Pull request status dashboard](https://mergebot.adhoc.ar/ingadhoc/purchase/pull/180).

**Comment by bruno-zanotti** [comment]
@roboadhoc r+

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Comment by fw-bot-adhoc** [comment]
@jjscarafia @Bruno-Zanotti this pull request has forward-port PRs awaiting action (not merged or closed):
- ingadhoc/purchase#184

**Pull request closed without merging**
